exports.palestras = [
	{id: 1, titulo: 'Node.js - Levando o poder do JavaScript para o servidor!', descricao: 'Nesta palestra, vamos abordar os conceitos fundamentais do Node.js, falando de sua arquitetura assíncrona e não bloqueante, e também de alguns de seus principais módulos. Além disso, faremos um hands-on, criando uma API para atender as requisições de um aplicativo escrito em AngularJS. ', palestrante: {nome: 'Rodrigo Branas'}},
	{id: 2, titulo: 'O que eu aprendi ficando offline', descricao: 'Os recursos offline possibilitam ganhos de usabilidade enorme, mas as técnicas como LocalStorage, AppCache, Cookies e IndexedDB exigem um domínio grande de assuntos que vão desde a correta configurações dos headers no servidor web até controles de execução assíncrona e ainda cuidados extra sobre segurança dos dados dos seus usuários. Se você ainda não está considerando funcionamento offline nos seus aplicativos, esta palestra vai te mostrar que logo você vai ficar pra trás. E se você precisa desconectar sem perder seu usuário, nesta palestra você vai conhecer o caminho das pedras e dar algumas boas dicas pra facilitar o seu trabalho. Usando um caso real de um aplicativo, Filipi vai apresentar tudo que ele aprendeu, os tropeços e os acertos para conseguir levar o aplicativo para produção totalmente desconectável.', palestrante: {nome: 'Filipi Zimermann'}},
	{id: 3, titulo: 'Por que Meteor?', descricao: 'Meteor é um projeto que surgiu no MIT, recebeu investimentos massivos e está se consolidando rapidamente como uma ferramenta que permite criar aplicações realtime para web e mobile utilizando apenas JavaScript. Nessa palestra pretendo apresentar os fundamentos desse framework, várias razões para adotá-lo em seu próximo projeto e exemplos de código demonstrando como ele é simples e ao mesmo tempo poderoso. ', palestrante: {nome: 'Filipe Portes'}},
	{id: 4, titulo: 'Otimizando seu JavaScript no V8', descricao: 'Vamos ver como quebrar as barreiras de velocidade do seu JavaScript no V8, a incrível engine open source do Google, que é utilizada tanto no Chrome como no Node.js. Entendendo como as coisas funcionam por baixo dos panos, vamos ver que já é possível comparações impensáveis antes, como a velocidade de execução de códigos em Javascript e C++. ', palestrante: {nome: 'William Grasel Martins'}},
	{id: 5, titulo: 'Aplicações off-line first com Ionic e PouchDB', descricao: 'Essa palestra, aborda os desafios acerca da criação de um chat com sincronia offline e realtime, usando Couchdb, Ionic e Pouchdb e com baixo custo. ', palestrante: {nome: 'Itacir Ferreira Pompeu'}},
	{id: 6, titulo: 'Gerenciando seus assets com webpack', descricao: 'Gerenciar assets em uma aplicação de todos os tamanhos é algo que sempre damanda tempo dos desenvolvedores e na maioria das vezes torna-se algo complexo e difícil de dar manutenção. Para lidar com isso foi criado o webpack, um bundler que irá gerenciar todos seus assets, desde imagens até estilos. ', palestrante: {nome: 'Matheus Lucca do Carmo'}},
	{id: 7, titulo: 'Testando APIs REST com Supertest e Promises ', descricao: 'Nesta palestra, veremos como testar suas APIs REST de forma simples usando o Supertest. Também veremos como criar testes mais complexos sem medo de cair em um callback hell, usando Promises. No final, teremos um hands-on, criando e rodando alguns testes. ', palestrante: {nome: 'Stefan Raphael de Araújo Teixeira'}},
	{id: 8, titulo: 'Filtrando o TimeZone com Momentjs', descricao: 'Aprenda de uma forma prática, a controlar o TimeZone de sua aplicação JavaScript utilizando a biblioteca momentjs. ', palestrante: {nome: 'Danilo Raulino de Liz'}},
	{id: 9, titulo: 'JavaScript Promises na prática', descricao: 'Sofrendo com callback hell? Afim de padronizar seu código assíncrono? Promises são a resposta! Assista essa palestra e entenda como se livrar do sofrimento! ', palestrante: {nome: 'Derek Stavis'}},
	{id: 10, titulo: 'Olá, Typescript', descricao: 'Javascript nasceu, cresceu, amadureceu e agora está em tudo, aonde olhamos podemos ver um pouco dele, seja em um decoder de TV Digital, até no aplicativo preferido do seu celular. Junto com essa evolução, também surgiram algumas ferramentas que auxiliam no seu desenvolvimento, uma delas é o Typescript, um conjunto de ferramentas que auxilia na forma como você e sua equipe escrevem javascript. Vamos ver o que é, de onde vem, porque ele existe e para onde pretende ir o Typescript. ', palestrante: {nome: 'Guilherme Waess da Rocha'}}
];